# =============================================================================
# Program      : 14_chain_of_custody_test.py
# Version      : 1.0
# Description  : Multi-Generation Chain-of-Custody Test (T-IFS expansion).
#
#                Every prior attack in this project applies ONE transform
#                (or one attack) to freshly-embedded audio and reports the
#                result. Real content doesn't have a one-hop lifecycle —
#                it gets compressed for one platform, re-shared, possibly
#                regenerated by AI at some point, re-compressed again,
#                shared further. The forensic question this raises, and
#                which nothing built so far answers, is: if a regeneration
#                event happens partway through a realistic processing
#                history, does it remain detectable after MORE benign
#                processing on top of it, or does the evidence get buried?
#                Conversely, does a long chain of PURELY benign processing
#                ever accumulate enough drift to look like a false
#                regeneration signal?
#
#                FIVE 4-HOP CHAINS, using the same fixed pool of benign
#                transforms (MP3@128kbps, resample@22050Hz, noise@30dB SNR,
#                gain@0.85 — moderate, representative settings, not a
#                battery sweep) and DAC (proven fast, full-clip real
#                regeneration) as the regeneration step, so results are
#                directly comparable across chains:
#                  all_benign    : compress -> resample -> noise -> gain
#                  regen_first   : DAC -> compress -> resample -> noise
#                  regen_last    : compress -> resample -> noise -> DAC
#                  regen_middle  : compress -> DAC -> resample -> noise
#                  double_regen  : DAC -> compress -> DAC -> resample
#
#                BER for BOTH Path A and Path B is tracked AFTER EVERY
#                HOP, not just at the end — the trajectory across the
#                chain is the actual result here, not a single number.
#                Uses the DEFENDER's real trained system (05's joint
#                checkpoint) throughout; no attacker model in this
#                experiment, no training — pure evaluation of an already-
#                trained system's behavior over a realistic lifecycle.
#
# PRE-FLIGHT SELF-TEST: confirms the E3 checkpoint reproduces its own
# known single-hop behavior (BER~0 benign for both paths) before running
# any multi-hop chain — isolates whether any chain-position effect
# observed later is real, not an artifact of a broken checkpoint load.
#
# INPUT:
#                  PROJECT_DIR (/content/drive/MyDrive/paper/HyperFrag/):
#                    dataset_e0.h5              — from 01_e0_dataextract.py
#                    e3_joint_checkpoint.pth    — from 05_e3_joint_path.py
#                                                 (REQUIRED)
#
# STEPS:
#                  Step 1  Download dataset_e0.h5 + e3_joint_checkpoint.pth
#                          from PROJECT_DIR
#                  Step 2  Load frozen EnCodec + DAC, slim self-test
#                  Step 3  Load E3's trained joint checkpoint, self-test
#                          single-hop behavior matches known results
#                  Step 4  For each of 105 held-out clips: embed jointly,
#                          then run all 5 chains, scoring Path A and Path
#                          B BER after every hop of every chain
#                  Step 5  Save per-chain, per-hop-position BER
#                          trajectories; generate trajectory figure
#
# OUTPUT FILES : (stored at /content/drive/MyDrive/paper/HyperFrag/)
#                  exp14_chain_of_custody_results.json
#                      {chain_name: {path_a: [ber_hop1..4], path_b: [ber_hop1..4]}}
#                  fig_14_01_chain_trajectories.png
#                      BER vs. hop position, one line per chain, separate
#                      panels for Path A and Path B — does regeneration's
#                      signature persist, and does chain position matter?
#
# GPU Required : YES
# Dependencies : torch, torchaudio, encodec, pydub, descript-audio-codec,
#                h5py, matplotlib, tqdm
#
# Change Log   :
#   v1.0  2026-07-28  Initial version
#
# !pip install torch torchaudio encodec pydub descript-audio-codec h5py matplotlib tqdm
# =============================================================================

!pip install -q encodec pydub descript-audio-codec h5py matplotlib tqdm

import torch

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
if not torch.cuda.is_available():
    print("\n[ERROR] GPU not detected!")
    import sys
    sys.exit(1)
print("CUDA available: True. Proceeding...")

torch.backends.cudnn.enabled = False  # same LSTM/eval-mode fix as every training/eval script here

import os
import json
import random
import shutil
import time
import datetime
import tempfile

import numpy as np
import h5py
import torch.nn as nn
import torch.nn.functional as F
import torchaudio
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from tqdm import tqdm
from encodec import EncodecModel

SR = 24000
TARGET_BANDWIDTH_KBPS = 6.0
KEY_BITS = 4
VAL_FRACTION = 0.10
SEED = 20260716  # SAME seed — identical 105-clip split as every other experiment
N_EVAL_CLIPS = 105

random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)


def now():
    return datetime.datetime.now().strftime("%H:%M:%S")


# --- Google Drive Helper Functions --------------------------------------------
PROJECT_DIR = "/content/drive/MyDrive/paper/HyperFrag/"
MAX_RETRIES = 3
TIMEOUT_SECONDS = 60


def copy_to_project(local_filepath, remote_filename):
    """Copy a local file to PROJECT_DIR (Google Drive)."""
    project_filepath = os.path.join(PROJECT_DIR, remote_filename)
    os.makedirs(os.path.dirname(project_filepath), exist_ok=True)
    for attempt in range(1, MAX_RETRIES + 1):
        try:
            shutil.copy2(local_filepath, project_filepath)
            return
        except Exception as e:
            print(f"[PROJECT_DIR] copy attempt {attempt}/{MAX_RETRIES} for "
                  f"{remote_filename} failed: {e}")
            if attempt == MAX_RETRIES:
                raise
            time.sleep(5)


def copy_from_project(remote_filename, local_filepath, verbose=True, skip_if_exists=True):
    """Copy a file from PROJECT_DIR (Google Drive) to local path."""
    project_filepath = os.path.join(PROJECT_DIR, remote_filename)
    if not os.path.isfile(project_filepath):
        print(f"[PROJECT_DIR] {remote_filename} not found in PROJECT_DIR")
        return False
    
    if skip_if_exists and os.path.exists(local_filepath):
        local_size = os.path.getsize(local_filepath)
        remote_size = os.path.getsize(project_filepath)
        if remote_size == local_size:
            print(f"[PROJECT_DIR] {local_filepath} already exists locally "
                  f"({local_size / 1e6:.1f} MB), skipping copy.")
            return True
        print(f"[PROJECT_DIR] {local_filepath} exists locally but size differs from "
              f"PROJECT_DIR ({local_size} vs {remote_size} bytes) — re-copying.")
    
    for attempt in range(1, MAX_RETRIES + 1):
        try:
            os.makedirs(os.path.dirname(local_filepath), exist_ok=True)
            total_size = os.path.getsize(project_filepath)
            
            with open(local_filepath, "wb") as f, tqdm(
                total=total_size, unit="B", unit_scale=True, unit_divisor=1024,
                desc=f"[PROJECT_DIR] {remote_filename}", disable=not verbose,
            ) as pbar:
                with open(project_filepath, "rb") as src:
                    while True:
                        chunk = src.read(8192)
                        if not chunk:
                            break
                        f.write(chunk)
                        pbar.update(len(chunk))
            return True
        except Exception as e:
            print(f"[PROJECT_DIR] download attempt {attempt}/{MAX_RETRIES} for "
                  f"{remote_filename} failed: {e}")
            if attempt == MAX_RETRIES:
                return False
            time.sleep(5)
    return False


def project_file_exists(remote_filename):
    """Check if a file exists in PROJECT_DIR (Google Drive)."""
    project_filepath = os.path.join(PROJECT_DIR, remote_filename)
    return os.path.isfile(project_filepath)


LOCAL_SCRATCH = "/content/scratch"
os.makedirs(LOCAL_SCRATCH, exist_ok=True)
LOCAL_H5 = f"{LOCAL_SCRATCH}/dataset_e0.h5"
LOCAL_E3_CKPT = f"{LOCAL_SCRATCH}/e3_joint_checkpoint.pth"
LOCAL_RESULTS = f"{LOCAL_SCRATCH}/exp14_chain_of_custody_results.json"
LOCAL_FIG = f"{LOCAL_SCRATCH}/fig_14_01_chain_trajectories.png"


# --- Corpus ---------------------------------------------------------------
def load_val_clips():
    print(f"[{now()}] Downloading dataset_e0.h5 from PROJECT_DIR...")
    if not copy_from_project("dataset_e0.h5", LOCAL_H5):
        raise SystemExit("dataset_e0.h5 not found in PROJECT_DIR — run 01_e0_dataextract.py first.")
    ids, wavs = [], []
    with h5py.File(LOCAL_H5, "r") as h5f:
        for gid in ("jamendo", "musdb18"):
            for tid in h5f[gid].keys():
                ids.append(tid)
                wavs.append(h5f[gid][tid][:])
    wavs = np.stack(wavs).astype(np.float32)
    idx = np.arange(len(ids))
    rng = np.random.RandomState(SEED)
    rng.shuffle(idx)
    n_val = int(len(idx) * VAL_FRACTION)
    val_idx = idx[:n_val]
    print(f"[{now()}] {len(val_idx)} held-out clips (identical split to every other experiment).")
    return wavs[val_idx]


# --- Frozen EnCodec + DAC + slim self-test ----------------------------------
def load_models_and_selftest(sample_wav_np):
    print(f"[{now()}] Loading frozen EnCodec (24kHz)...")
    model = EncodecModel.encodec_model_24khz()
    model.set_target_bandwidth(TARGET_BANDWIDTH_KBPS)
    model.eval()
    for p in model.parameters():
        p.requires_grad_(False)
    model = model.to(DEVICE)
    frame_rate = getattr(model, "frame_rate", 75)
    bandwidth = getattr(model, "bandwidth", TARGET_BANDWIDTH_KBPS)

    with torch.no_grad():
        d_total = model.encoder(torch.zeros(1, 1, SR, device=DEVICE)).shape[1]
    d_a_start, d_a_end = 0, d_total // 4
    d_b_start, d_b_end = d_total // 4, 2 * (d_total // 4)
    print(f"[{now()}] D_total={d_total}. Path A [{d_a_start}:{d_a_end}], Path B [{d_b_start}:{d_b_end}].")

    print(f"[{now()}] Loading DAC (24kHz)...")
    import dac
    dac_model_path = dac.utils.download(model_type="24khz")
    dac_model = dac.DAC.load(dac_model_path).to(DEVICE)
    dac_model.eval()

    return model, dac_model, d_total, d_a_start, d_a_end, d_b_start, d_b_end, frame_rate, bandwidth


# --- Trainable modules (identical architecture) ------------------------------
class HyperNet(nn.Module):
    def __init__(self, key_bits, d_channels, hidden=128):
        super().__init__()
        self.d_channels = d_channels
        self.net = nn.Sequential(
            nn.Linear(key_bits, hidden), nn.ReLU(),
            nn.Linear(hidden, hidden), nn.ReLU(),
            nn.Linear(hidden, 2 * d_channels),
        )

    def forward(self, key_bits):
        out = self.net(key_bits)
        gamma_raw, beta_raw = out[:, :self.d_channels], out[:, self.d_channels:]
        gamma = 1.0 + 0.5 * torch.tanh(gamma_raw)
        beta = 0.5 * torch.tanh(beta_raw)
        return gamma, beta


class Extractor(nn.Module):
    def __init__(self, key_bits, channels=32):
        super().__init__()
        def block(cin, cout, stride):
            return nn.Sequential(
                nn.Conv1d(cin, cout, kernel_size=9, stride=stride, padding=4),
                nn.BatchNorm1d(cout), nn.ReLU(),
            )
        self.net = nn.Sequential(
            block(1, channels, 4),
            block(channels, channels * 2, 4),
            block(channels * 2, channels * 4, 4),
            block(channels * 4, channels * 4, 4),
            block(channels * 4, channels * 4, 4),
            nn.AdaptiveAvgPool1d(1),
        )
        self.head = nn.Linear(channels * 4, key_bits)

    def forward(self, wav):
        h = self.net(wav.unsqueeze(1)).squeeze(-1)
        return self.head(h)


def embed_joint(model, wav_1ch, hypernet_a, hypernet_b, key_a, key_b,
                 d_a_start, d_a_end, d_b_start, d_b_end, frame_rate, bandwidth):
    with torch.no_grad():
        raw_emb = model.encoder(wav_1ch)
        gamma_a, beta_a = hypernet_a(key_a)
        gamma_b, beta_b = hypernet_b(key_b)
        gamma_a, beta_a = gamma_a.unsqueeze(-1), beta_a.unsqueeze(-1)
        gamma_b, beta_b = gamma_b.unsqueeze(-1), beta_b.unsqueeze(-1)
        emb_a = raw_emb[:, d_a_start:d_a_end, :] * gamma_a + beta_a
        emb_b = raw_emb[:, d_b_start:d_b_end, :] * gamma_b + beta_b
        emb_mod = torch.cat([emb_a, emb_b, raw_emb[:, d_b_end:, :]], dim=1)
        qres = model.quantizer(emb_mod, frame_rate, bandwidth)
        return model.decoder(qres.quantized)


def match_length(wav_1ch, target_len):
    cur = wav_1ch.shape[-1]
    if cur == target_len:
        return wav_1ch
    if cur > target_len:
        return wav_1ch[..., :target_len]
    return F.pad(wav_1ch, (0, target_len - cur))


# --- Chain step implementations (all take/return [1,1,T] tensors) ----------
def real_mp3_roundtrip_1ch(wav_1ch, bitrate_kbps=128):
    from pydub import AudioSegment
    import soundfile as sf
    wav_np = wav_1ch.squeeze().cpu().numpy()
    with tempfile.NamedTemporaryFile(suffix=".wav") as wav_f, \
         tempfile.NamedTemporaryFile(suffix=".mp3") as mp3_f:
        sf.write(wav_f.name, wav_np, SR)
        AudioSegment.from_wav(wav_f.name).export(mp3_f.name, format="mp3", bitrate=f"{bitrate_kbps}k")
        seg = AudioSegment.from_mp3(mp3_f.name)
        out = np.array(seg.get_array_of_samples()).astype(np.float32)
        if seg.channels > 1:
            out = out.reshape(-1, seg.channels).mean(axis=1)
        out = out / (2 ** (8 * seg.sample_width - 1))
        if seg.frame_rate != SR:
            out = torchaudio.functional.resample(
                torch.from_numpy(out).unsqueeze(0), seg.frame_rate, SR).squeeze(0).numpy()
    out_t = torch.from_numpy(out).float().to(DEVICE).unsqueeze(0).unsqueeze(0)
    return match_length(out_t, wav_1ch.shape[-1])


def resample_roundtrip_1ch(wav_1ch, target_rate=22050):
    down = torchaudio.functional.resample(wav_1ch, SR, target_rate)
    return torchaudio.functional.resample(down, target_rate, SR)


def add_noise_1ch(wav_1ch, snr_db=30):
    sig_power = wav_1ch.pow(2).mean(dim=-1, keepdim=True)
    noise_power = sig_power / (10 ** (snr_db / 10))
    return wav_1ch + torch.randn_like(wav_1ch) * noise_power.sqrt()


def apply_gain_1ch(wav_1ch, g=0.85):
    return wav_1ch * g


def dac_regen_1ch(dac_model, wav_1ch):
    with torch.no_grad():
        x = dac_model.preprocess(wav_1ch, SR)
        z, codes, latents, _, _ = dac_model.encode(x)
        y = dac_model.decode(z)
    return match_length(y, wav_1ch.shape[-1])


# Fixed step pool — moderate, representative settings, not a sweep. Each
# chain below is a specific ordered sequence of these, held constant
# across all 105 clips for direct comparability.
def step_compress(wav_1ch):
    return real_mp3_roundtrip_1ch(wav_1ch, 128)


def step_resample(wav_1ch):
    return resample_roundtrip_1ch(wav_1ch, 22050)


def step_noise(wav_1ch):
    return add_noise_1ch(wav_1ch, 30)


def step_gain(wav_1ch):
    return apply_gain_1ch(wav_1ch, 0.85)


def step_dac(wav_1ch, dac_model):
    return dac_regen_1ch(dac_model, wav_1ch)


CHAINS = {
    "all_benign":   ["compress", "resample", "noise", "gain"],
    "regen_first":  ["dac", "compress", "resample", "noise"],
    "regen_last":   ["compress", "resample", "noise", "dac"],
    "regen_middle": ["compress", "dac", "resample", "noise"],
    "double_regen": ["dac", "compress", "dac", "resample"],
}


def run_step(step_name, wav_1ch, dac_model):
    if step_name == "compress":
        return step_compress(wav_1ch)
    if step_name == "resample":
        return step_resample(wav_1ch)
    if step_name == "noise":
        return step_noise(wav_1ch)
    if step_name == "gain":
        return step_gain(wav_1ch)
    if step_name == "dac":
        return step_dac(wav_1ch, dac_model)
    raise ValueError(f"Unknown step: {step_name}")


# --- Self-test: E3 checkpoint reproduces its own known single-hop behavior -
def selftest_checkpoint(model, hypernet_a, extractor_a, hypernet_b, extractor_b,
                         d_a_start, d_a_end, d_b_start, d_b_end, frame_rate, bandwidth, sample_wav_np):
    print(f"[{now()}] Self-test: E3 checkpoint reproduces known single-hop clean-signal behavior...")
    wav_t = torch.from_numpy(sample_wav_np).float().unsqueeze(0).unsqueeze(0).to(DEVICE)
    key_a = (torch.randint(0, 2, (1, KEY_BITS), device=DEVICE) * 2 - 1).float()
    key_b = (torch.randint(0, 2, (1, KEY_BITS), device=DEVICE) * 2 - 1).float()
    target_a = (key_a > 0).float()
    target_b = (key_b > 0).float()
    x_wm = embed_joint(model, wav_t, hypernet_a, hypernet_b, key_a, key_b,
                        d_a_start, d_a_end, d_b_start, d_b_end, frame_rate, bandwidth)
    with torch.no_grad():
        pred_a = (extractor_a(x_wm.squeeze(1)) > 0).float()
        pred_b = (extractor_b(x_wm.squeeze(1)) > 0).float()
    n_wrong_a = int((pred_a != target_a).sum().item())
    n_wrong_b = int((pred_b != target_b).sum().item())
    print(f"[selftest] clean-signal bits wrong — Path A: {n_wrong_a}/{KEY_BITS}, "
          f"Path B: {n_wrong_b}/{KEY_BITS} (expect close to 0 for both, matching "
          f"E3's own reported ~0.01-0.03 / ~0.09-0.11 benign BER)")
    if n_wrong_a > KEY_BITS // 2 or n_wrong_b > KEY_BITS // 2:
        raise SystemExit("Self-test failed — checkpoint does not reproduce known clean-signal behavior.")
    print(f"[selftest] PASSED.")


# --- Main ---------------------------------------------------------------
def main():
    val_wavs = load_val_clips()
    (model, dac_model, d_total, d_a_start, d_a_end, d_b_start, d_b_end,
     frame_rate, bandwidth) = load_models_and_selftest(val_wavs[0])

    print(f"[{now()}] Downloading e3_joint_checkpoint.pth from PROJECT_DIR (REQUIRED)...")
    if not copy_from_project("e3_joint_checkpoint.pth", LOCAL_E3_CKPT):
        raise SystemExit("e3_joint_checkpoint.pth not found in PROJECT_DIR — run "
                          "05_e3_joint_path.py to completion first.")
    ckpt = torch.load(LOCAL_E3_CKPT, map_location=DEVICE)
    hypernet_a = HyperNet(KEY_BITS, d_a_end - d_a_start).to(DEVICE)
    extractor_a = Extractor(KEY_BITS).to(DEVICE)
    hypernet_b = HyperNet(KEY_BITS, d_b_end - d_b_start).to(DEVICE)
    extractor_b = Extractor(KEY_BITS).to(DEVICE)
    hypernet_a.load_state_dict(ckpt["hypernet_a_state"])
    extractor_a.load_state_dict(ckpt["extractor_a_state"])
    hypernet_b.load_state_dict(ckpt["hypernet_b_state"])
    extractor_b.load_state_dict(ckpt["extractor_b_state"])
    for m in (hypernet_a, extractor_a, hypernet_b, extractor_b):
        m.eval()
    print(f"[{now()}] Loaded E3 checkpoint from epoch {ckpt.get('epoch')}.")

    selftest_checkpoint(model, hypernet_a, extractor_a, hypernet_b, extractor_b,
                         d_a_start, d_a_end, d_b_start, d_b_end, frame_rate, bandwidth, val_wavs[0])

    eval_wavs = val_wavs[:N_EVAL_CLIPS]
    n_hops = 4
    # results[chain_name]["path_a"/"path_b"] = list of n_hops lists, each with n_clips BER contributions
    results = {name: {"path_a": [{"wrong": 0, "total": 0} for _ in range(n_hops)],
                       "path_b": [{"wrong": 0, "total": 0} for _ in range(n_hops)]}
               for name in CHAINS}

    print(f"[{now()}] Running {len(CHAINS)} chains x {n_hops} hops on {len(eval_wavs)} clips...")
    for i in tqdm(range(len(eval_wavs)), desc="chain-of-custody"):
        wav_t = torch.from_numpy(eval_wavs[i]).float().unsqueeze(0).unsqueeze(0).to(DEVICE)
        key_a = (torch.randint(0, 2, (1, KEY_BITS), device=DEVICE) * 2 - 1).float()
        key_b = (torch.randint(0, 2, (1, KEY_BITS), device=DEVICE) * 2 - 1).float()
        target_a = (key_a > 0).float()
        target_b = (key_b > 0).float()

        with torch.no_grad():
            x_wm = embed_joint(model, wav_t, hypernet_a, hypernet_b, key_a, key_b,
                                d_a_start, d_a_end, d_b_start, d_b_end, frame_rate, bandwidth)

        for chain_name, steps in CHAINS.items():
            current = x_wm
            for hop_idx, step_name in enumerate(steps):
                with torch.no_grad():
                    current = run_step(step_name, current, dac_model)
                    current_flat = current.squeeze(1)
                    pred_a = (extractor_a(current_flat) > 0).float()
                    pred_b = (extractor_b(current_flat) > 0).float()
                results[chain_name]["path_a"][hop_idx]["wrong"] += int((pred_a != target_a).sum().item())
                results[chain_name]["path_a"][hop_idx]["total"] += KEY_BITS
                results[chain_name]["path_b"][hop_idx]["wrong"] += int((pred_b != target_b).sum().item())
                results[chain_name]["path_b"][hop_idx]["total"] += KEY_BITS

    ber_results = {}
    for chain_name in CHAINS:
        ber_results[chain_name] = {
            "steps": CHAINS[chain_name],
            "path_a_ber_by_hop": [float(d["wrong"] / d["total"]) for d in results[chain_name]["path_a"]],
            "path_b_ber_by_hop": [float(d["wrong"] / d["total"]) for d in results[chain_name]["path_b"]],
        }

    output = {"chains": ber_results, "n_clips": len(eval_wavs), "key_bits": KEY_BITS,
              "step_settings": {"compress": "MP3@128kbps", "resample": "22050Hz",
                                 "noise": "30dB SNR", "gain": "0.85", "dac": "24kHz full-clip"}}
    with open(LOCAL_RESULTS, "w") as f:
        json.dump(output, f, indent=2)
    copy_to_project(LOCAL_RESULTS, "exp14_chain_of_custody_results.json")

    for chain_name, r in ber_results.items():
        print(f"[{now()}] {chain_name} ({' -> '.join(r['steps'])}):")
        print(f"    Path A BER by hop: {[f'{b:.3f}' for b in r['path_a_ber_by_hop']]}")
        print(f"    Path B BER by hop: {[f'{b:.3f}' for b in r['path_b_ber_by_hop']]}")

    fig, axes = plt.subplots(1, 2, figsize=(14, 5.5))
    hop_x = list(range(1, n_hops + 1))
    colors = plt.cm.tab10(np.linspace(0, 1, len(CHAINS)))
    for (chain_name, r), color in zip(ber_results.items(), colors):
        axes[0].plot(hop_x, r["path_a_ber_by_hop"], "o-", label=chain_name, color=color)
        axes[1].plot(hop_x, r["path_b_ber_by_hop"], "o-", label=chain_name, color=color)
    for ax, title in zip(axes, ["Path A (robust) BER by hop position", "Path B (fragile) BER by hop position"]):
        ax.axhline(0.5, color="gray", linestyle="--", alpha=0.4, label="chance")
        ax.set_xlabel("Hop position in chain")
        ax.set_ylabel("BER")
        ax.set_title(title)
        ax.set_xticks(hop_x)
        ax.legend(fontsize=7)
    fig.suptitle(f"Multi-generation chain-of-custody test — n={len(eval_wavs)} held-out clips, "
                 f"5 chains x 4 hops")
    fig.tight_layout()
    fig.savefig(LOCAL_FIG, dpi=300)
    plt.close(fig)
    copy_to_project(LOCAL_FIG, "fig_14_01_chain_trajectories.png")

    print(f"[{now()}] DONE. exp14_chain_of_custody_results.json, "
          f"fig_14_01_chain_trajectories.png all saved to PROJECT_DIR.")


if __name__ == "__main__":
    main()